# Generated by Django 3.1.2 on 2020-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='end_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='goals',
            name='start_time',
            field=models.DateField(),
        ),
    ]
