# Generated by Django 3.1.2 on 2020-11-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
