# Generated by Django 3.1.2 on 2020-11-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201111_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
